"""Generated filter banks for Unit: parametric families (train_parametric) and non-parametric multiscale banks (train_multiscale)."""
from ._base import *


class _Banks:
    """Unit methods: parametric and multiscale filter banks"""

    #- parametric filter banks
    def _parametric_init(self,family,n,bTied,init,b2D):
        init=dict(init or {})
        kTop=float(init.get('kTop',0.25))                   # peak frequency of the first filter, cycles per sample
        ratio=float(init.get('ratio',2.0))                  # scale ratio between adjacent filters (tied banks)
        rd=jnp.finfo(self.nrn.dtype).dtype
        full=lambda v: jnp.full((n,),v,dtype=rd) if not bTied else jnp.asarray(v,dtype=rd)
        params={}
        if bTied:
            params['log_kTop']=jnp.asarray(np.log(kTop),dtype=rd)
            params['log_ratio_m1']=jnp.asarray(np.log(ratio-1),dtype=rd)
        else:
            params['log_kPeak']=jnp.asarray(np.log(kTop/ratio**np.arange(n)),dtype=rd)
        if family=='morse':
            params['log_gamma']=full(np.log(float(init.get('gamma',2.0))))
            params['log_b']=full(np.log(float(init.get('b',2.0))))
        elif family=='loggabor':
            params['log_sigma_u']=full(np.log(float(init.get('sigma_u',0.5))))
        else:
            raise Exception("family must be 'morse' or 'loggabor'")
        if b2D:
            params['log_sigma_theta']=full(np.log(float(init.get('sigma_theta',np.deg2rad(20)))))
        return params

    def _parametric_filters(self,params,family,n,bTied,orientations):
        """unit-norm fourier-domain filters [ nPix x nF ] on the learned half-space coefficients"""
        flt=self.filter
        pix_dims=flt.pix_dims
        grids=np.meshgrid(*[_centered_freqs(d) for d in pix_dims],indexing='ij')
        kr=np.sqrt(sum(g**2 for g in grids)).ravel()[flt.index.pix]             # [ nPix_learned ]
        e=jnp.exp
        if bTied:
            kPeak=e(params['log_kTop'])/(1+e(params['log_ratio_m1']))**jnp.arange(n)
        else:
            kPeak=e(params['log_kPeak'])
        x=kr[:,None]/kPeak[None,:]                                               # [ nPix_learned x nF ]
        lx=jnp.log(jnp.maximum(x,1e-30))
        if family=='morse':
            gam,b=e(params['log_gamma']),e(params['log_b'])
            lprof=b*lx + (b/gam)*(1-jnp.exp(gam*lx))                             # peak 1 at x = 1
        else:
            su=e(params['log_sigma_u'])
            lprof=-lx**2/(2*su**2)
        if len(pix_dims)==2:
            ang=np.arctan2(grids[1],grids[0]).ravel()[flt.index.pix]
            d=(ang[:,None]-np.asarray(orientations)[None,:]+np.pi)%(2*np.pi)-np.pi
            st=e(params['log_sigma_theta'])
            lprof=lprof - d**2/(2*st**2) + jnp.where(np.cos(d)>0,0.,-jnp.inf)
        prof=jnp.exp(jnp.maximum(lprof,-700.))
        prof=prof/jnp.linalg.norm(prof,axis=0,keepdims=True)
        f=jnp.zeros((int(np.prod(pix_dims)),n),dtype=self.nrn.dtype)
        return f.at[flt.index.pix].set(prof.astype(self.nrn.dtype))

    def _train_generated(self,params,kind,cfg,stimVal=None):
        """
        optimize params (a dict of arrays; 'p' holds readout pooling weights) of the filters generated by kind ('parametric'
        or 'multiscale', see _generated_filters) with configuration cfg, on this unit's cost plus the generator's penalty,
        with this unit's Optimizer (optimizerType, lRate0, nIterMax, nStepsPerChunk, batchSize, bVerbose, patience with
        stimVal). Returns the final (or best validation) params.
        """
        loss=_GeneratedLoss(self,kind,cfg)
        val_fun=None
        if stimVal is not None:
            test=self._prepare_stim(stimVal)
            val_fun=lambda prm: _generated_heldout(loss,prm,self.rng,test.val,test.weights,test.yCtg,test.Y,
                                                   self.stim.val,self.stim.weights,self.stim.yCtg)
        rng,_=jxrandom.split(self.rng)
        params,self.rng_last=self.optimizer.minimize_generated(params,rng,self.stim,loss,val_fun)
        return params

    def _generated_filters(self,kind,params,cfg):
        # filters [ nPix x nF ] generated from params; with a learned phase (bPhase) each filter's spectrum is rotated by it
        if kind=='parametric':
            f=self._parametric_filters(params,cfg['family'],cfg['n'],cfg['bTied'],cfg['orientations'])
        else:
            f=self._multiscale_filters(params,cfg['nTot'],cfg)
        if 'phase' in params:
            f=f*jnp.exp(1j*params['phase']).astype(f.dtype)[None,:]
        return f

    def _generated_penalty(self,kind,params,cfg):
        # multiscale knotSmooth: squared second differences of each mother's tapered knots, relative to its energy
        if kind!='multiscale' or not cfg['knotSmooth']>0:
            return None
        nMothers=cfg['nMothers']
        tm=self._tapered_mothers(params,cfg)
        energy=jnp.sum((jnp.abs(tm)**2).reshape(nMothers,-1),axis=1)+1e-12
        tot=0.
        for v in (jnp.real(tm),jnp.imag(tm)):
            d=jnp.sum((jnp.diff(v,n=2,axis=1)**2).reshape(nMothers,-1),axis=1)
            if tm.ndim==3:                                                   # 2D: also along angle
                d=d+jnp.sum((jnp.diff(v,n=2,axis=2)**2).reshape(nMothers,-1),axis=1)
            tot=tot+jnp.sum(d/energy)
        return cfg['knotSmooth']*tot

    def _set_generated(self,f,params):
        # generated filters [ nPix x nF ] become this unit's ordinary filters
        self.filter.out=jnp.reshape(f,self.filter._shape_exp)
        self.out_params={'f':f[self.filter._insert_index_jx]}
        self._opt_param_shape=self.out_params['f'].shape
        self._opt_state_key=None
        self.opt_state=None
        if 'p' in params:
            self._set_p(params['p'])

    #- non-parametric multiscale filter banks
    @staticmethod
    def _interp_uniform(x,x0,dx,v):
        """
        linear interpolation of knot values v [ nKnot x ... ] on the uniform grid x0 + dx*arange(nKnot) at points x
        [ nPts x ... ] (broadcast), zero outside the grid
        """
        n=v.shape[0]
        t=(x-x0)/dx
        i=jnp.floor(t)
        w=t-i
        i=i.astype(int)
        inside=(t>=0)&(t<=n-1)
        i0=jnp.clip(i,0,n-1)
        i1=jnp.clip(i+1,0,n-1)
        val=v[i0]*(1-w)+v[i1]*w
        return jnp.where(inside,val,0.)

    @staticmethod
    def _knot_taper(nKnot,edgeTaper):
        """[ nKnot ] window: cosine from 0 at the outermost knots to 1 over a fraction edgeTaper of the knot range at each end"""
        t=np.linspace(0.,1.,nKnot)
        d=np.minimum(t,1-t)
        if edgeTaper<=0:
            return np.ones(nKnot)
        return np.where(d<edgeTaper,0.5*(1-np.cos(np.pi*d/edgeTaper)),1.)

    @staticmethod
    def _tapered_mothers(params,cfg):
        """complex mother knots [ nMothers x nKnot (x nKnotTheta) ] after the log-frequency edge taper"""
        w=jnp.asarray(cfg.get('knotTaper',np.ones(params['mother_re'].shape[1])),dtype=params['mother_re'].dtype)
        w=w.reshape((1,-1)+(1,)*(params['mother_re'].ndim-2))
        return (params['mother_re'] + 1j*params['mother_im'])*w

    def _multiscale_filters(self,params,n,cfg):
        """
        dilated (and, in 2D, rotated) copies of non-parametric mother filters, as unit-norm fourier-domain filters
        [ nPix x nF ]. Each mother is complex knot values over log(k/k_peak) (1D: [ nKnot ]; 2D: [ nKnot x nKnotTheta ]
        over log radius and angle), linearly interpolated; params hold [ nMothers x ... ]. Filter order: mother first,
        then the scale (and orientation) filters of cfg (every mother shares the same scales and orientations).
        """
        flt=self.filter
        pix_dims=flt.pix_dims
        grids=np.meshgrid(*[_centered_freqs(d) for d in pix_dims],indexing='ij')
        kr=np.sqrt(sum(g**2 for g in grids)).ravel()[flt.index.pix]
        lk=np.log(np.maximum(kr,1e-12))                                           # [ nPts ]
        e=jnp.exp
        if cfg['scaleType']=='tied':
            # scaleExp: the scale step of each filter (0, 1, 2, ... ; +1/2 for interleaved filters)
            logPeak=params['log_kTop'] - jnp.log1p(e(params['log_ratio_m1']))*jnp.asarray(cfg['scaleExp'])
        elif cfg['scaleType']=='fixed':
            logPeak=jnp.asarray(np.log(cfg['kPeak']))
        else:
            logPeak=params['log_kPeak']
        mothers=self._tapered_mothers(params,cfg)                                 # [ nMothers x nKnot (x nKnotTheta) ]
        u=lk[:,None]-logPeak[None,:]                                              # [ nPts x nF_mother ] log(k/kPeak_j)
        uw=cfg['uWidth']
        du=2*uw/(cfg['nKnot']-1)
        allvals=[]
        for im in range(cfg.get('nMothers',1)):
          mother=mothers[im]
          if len(pix_dims)==1:
            vals=self._interp_uniform(u,-uw,du,mother)                            # mother [ nKnot ]
          else:
            ang=np.arctan2(grids[1],grids[0]).ravel()[flt.index.pix]
            d=(ang[:,None]-np.asarray(cfg['orientations'])[None,:]+np.pi)%(2*np.pi)-np.pi   # [ nPts x nF ]
            nT=cfg['nKnotTheta']
            dth=np.pi/(nT-1)
            # bilinear on [ log radius x angle in [-pi/2, pi/2] ]
            tu=(u+uw)/du
            tt=(d+np.pi/2)/dth
            iu=jnp.floor(tu); wu=tu-iu; iu=iu.astype(int)
            it=np.floor(tt); wt=tt-it; it=it.astype(int)
            inside=(tu>=0)&(tu<=cfg['nKnot']-1)&(tt>=0)&(tt<=nT-1)
            c=lambda a,m: jnp.clip(a,0,m-1)
            v00=mother[c(iu,cfg['nKnot']),c(it,nT)]
            v01=mother[c(iu,cfg['nKnot']),c(it+1,nT)]
            v10=mother[c(iu+1,cfg['nKnot']),c(it,nT)]
            v11=mother[c(iu+1,cfg['nKnot']),c(it+1,nT)]
            vals=((1-wu)*((1-wt)*v00+wt*v01)+wu*((1-wt)*v10+wt*v11))
            vals=jnp.where(inside,vals,0.)
          allvals.append(vals)
        vals=jnp.concatenate(allvals,axis=1)                                      # [ nPts x nMothers*nF_mother ]
        norm=jnp.sqrt(jnp.sum(jnp.abs(vals)**2,axis=0,keepdims=True))
        vals=vals/jnp.where(norm>0,norm,1)
        f=jnp.zeros((int(np.prod(pix_dims)),n),dtype=self.nrn.dtype)
        return f.at[flt.index.pix].set(vals.astype(self.nrn.dtype))

    @_logged_training
    def train_multiscale(self,n=None,fourierType=2,nKnot=25,uWidth=2.5,scaleType='tied',kTop=0.25,ratio=2.0,kPeak=None,
                         orientations=None,nKnotTheta=13,knotSmooth=0.,init='loggabor',dtype=None,stimVal=None,
                         nScales=None,nOrientations=None,bInterleave=False,nMothers=1,motherInitNoise=0.1,edgeTaper=0.,
                         bPhase=False):
        """
        learn a multiscale filter bank whose filters are copies of one (or nMothers) non-parametric mother filter: dilated (shifted in
        log frequency) and, for 2D stimuli, rotated (shifted in angle). The mother filter is free: complex spectrum values
        at nKnot points uniform over log(k/k_peak) in [-uWidth, uWidth] (2D: times nKnotTheta angles over [-pi/2, pi/2],
        one-sided), linearly interpolated, zero outside. Filters are unit norm, in the fourier domain (fourierType 1 or 2).

        scaleType - 'tied'  : peak frequencies kTop/ratio^j with kTop and ratio learned (initialized from kTop, ratio)
                    'fixed' : peak frequencies kPeak [ nF ] (default kTop/ratio^j), not learned
                    'free'  : a learned peak frequency per filter (initialized from kTop/ratio^j)
        orientations - 2D: [ nF ] radians from the first stimulus axis (default 0)
        knotSmooth   - weight of a penalty on squared second differences of the mother's knot values (smooth spectra)
        init         - initial mother: 'loggabor' (a real log-gaussian bump, sigma_u = uWidth/3) or 'random'
        nScales, nOrientations - 2D: build the filters as a grid instead of per-filter lists: peaks kTop/ratio^j
                       (j = 0..nScales-1) at orientations o*pi/nOrientations (o = 0..nOrientations-1, wrapped to
                       (-pi/2, pi/2]), n = nScales*nOrientations filters (n need not be given)
        bInterleave  - with the grid: add an interleaved set of the same size at the tritones (half a scale step,
                       kTop/ratio^(j+1/2): half an octave for ratio 2) in the half-rotations (orientations offset by
                       half the orientation step, pi/(2 nOrientations)). All filters are copies of the same mother;
                       with scaleType='tied' the interleaved scales stay halfway (in log frequency) as ratio is learned.
                       Filter order: the grid (scales x orientations, scale first), then the interleaved grid.
        nMothers     - learn this many mother filters simultaneously. Each gets the same set of scale (and orientation)
                       filters, so the bank has nMothers * n filters, ordered mother first; the scales (kTop and ratio,
                       kPeak, or the free peaks) and orientations are shared by all mothers. n (or the grid) counts the
                       filters per mother.
        edgeTaper    - force each mother to vanish at the ends of its log-frequency support: its knots are multiplied by a
                       fixed window that rises (cosine) from 0 at the outermost knots to 1 over this fraction of the knot
                       range at each end (0 = no taper; e.g. 0.2 tapers 5 of 25 knots per end). Without it a mother can
                       move its energy to the edge of the support, making its dilated copies narrowband filters cut off at
                       the boundary. The reported mother, the filters, and knotSmooth use the tapered knots. 2D: the taper
                       is along log radius only.
        motherInitNoise - with nMothers > 1, every mother's initial knots get independent complex gaussian noise of this
                       size relative to the initial bump (seeded from the unit's rng): identical mothers would receive
                       identical gradients and never diverge.
        bPhase       - also learn a phase per filter (exp(i phase) on its spectrum), so the dilated copies of a mother need
                       not share its phase (e.g. phase alignment across scales for a pooled readout)
        Uses this unit's Optimizer (and Objective regType on the generated filters is not applied; use knotSmooth).
        The learned filters become ordinary filters (unit.out); multiscale_values() returns the mother filter and scales.
        Not implemented for split stimuli.
        """
        if fourierType not in (1,2):
            raise Exception('train_multiscale learns in the fourier domain: fourierType must be 1 or 2')
        if scaleType not in ('tied','fixed','free'):
            raise Exception("scaleType must be 'tied', 'fixed', or 'free'")
        bGrid=nScales is not None or nOrientations is not None
        if bInterleave and not bGrid:
            raise Exception('bInterleave needs the filter grid: give nScales and nOrientations')
        scaleExp=None
        if bGrid:
            if nScales is None or nOrientations is None or nScales<1 or nOrientations<1:
                raise Exception('give both nScales and nOrientations (at least 1)')
            if kPeak is not None or orientations is not None:
                raise Exception('with nScales and nOrientations, kPeak and orientations are set by the grid')
            jj,oo=np.meshgrid(np.arange(nScales),np.arange(nOrientations),indexing='ij')
            scaleExp=jj.ravel().astype(float)
            orientations=oo.ravel()*np.pi/nOrientations
            if bInterleave:
                scaleExp=np.concatenate((scaleExp,scaleExp+0.5))
                orientations=np.concatenate((orientations,orientations+np.pi/(2*nOrientations)))
            orientations=(orientations+np.pi/2)%np.pi-np.pi/2                     # wrap to [-pi/2, pi/2)
            orientations=np.where(np.isclose(orientations,-np.pi/2),np.pi/2,orientations)
            nGrid=len(scaleExp)
            if n is not None and n!=nGrid:
                raise Exception('n (' + str(n) + ') does not match the grid (' + str(nGrid) + ' filters)')
            n=nGrid
        elif n is None:
            raise Exception('give n, or nScales and nOrientations')
        if nKnot<3 or (nKnotTheta is not None and nKnotTheta<2):
            raise Exception('nKnot must be at least 3 and nKnotTheta at least 2')
        nMothers=int(nMothers)
        if nMothers<1:
            raise Exception('nMothers must be at least 1')
        if not 0<=edgeTaper<=0.5:
            raise Exception('edgeTaper must be in [0, 0.5]')
        nTot=nMothers*n
        self.pool_p=self.nrn_p=None
        self._finalize(nTot,np.arange(nTot),fourierType=fourierType,dtype=dtype,bSplit=False)
        if len(self.filter.pix_dims) not in (1,2):
            raise Exception('train_multiscale supports 1D and 2D stimuli')
        b2D=len(self.filter.pix_dims)==2
        if bGrid and not b2D:
            raise Exception('nScales, nOrientations, and bInterleave need 2D stimuli (rotation)')
        orientations=np.zeros(n) if orientations is None else np.asarray(orientations,dtype=float)
        if b2D and orientations.shape!=(n,):
            raise Exception('orientations must have one value per filter')
        if scaleExp is None:
            scaleExp=np.arange(n,dtype=float)
        kPeak0=kTop/ratio**scaleExp if kPeak is None else np.asarray(kPeak,dtype=float)
        if kPeak0.shape!=(n,):
            raise Exception('kPeak must have one value per filter')
        rd=jnp.finfo(self.nrn.dtype).dtype
        cfg=dict(scaleType=scaleType,uWidth=float(uWidth),nKnot=int(nKnot),nKnotTheta=int(nKnotTheta),
                 orientations=orientations,kPeak=kPeak0,scaleExp=scaleExp,nMothers=nMothers,
                 knotTaper=self._knot_taper(int(nKnot),float(edgeTaper)),nTot=nTot,knotSmooth=float(knotSmooth))

        ug=np.linspace(-uWidth,uWidth,nKnot)
        if init=='loggabor':
            m=np.exp(-ug**2/(2*(uWidth/3)**2))
            if b2D:
                tg=np.linspace(-np.pi/2,np.pi/2,nKnotTheta)
                m=m[:,None]*np.exp(-tg[None,:]**2/(2*np.deg2rad(20)**2))
        elif init=='random':
            rng=np.random.default_rng(int(np.asarray(jxrandom.key_data(self.rng)).ravel()[-1]))
            m=rng.standard_normal((nKnot,nKnotTheta) if b2D else (nKnot,))
        else:
            raise Exception("init must be 'loggabor' or 'random'")
        m=np.broadcast_to(m,(nMothers,)+np.shape(m)).copy()
        mi=np.zeros(np.shape(m))
        if nMothers>1 and motherInitNoise>0:
            nrng=np.random.default_rng(int(np.asarray(jxrandom.key_data(self.rng)).ravel()[-1])+7919)
            scale=motherInitNoise*np.max(np.abs(m))
            m=m+scale*nrng.standard_normal(m.shape)
            mi=scale*nrng.standard_normal(m.shape)
        params={'mother_re':jnp.asarray(m,dtype=rd),'mother_im':jnp.asarray(mi,dtype=rd)}
        if scaleType=='tied':
            params['log_kTop']=jnp.asarray(np.log(kTop),dtype=rd)
            params['log_ratio_m1']=jnp.asarray(np.log(ratio-1),dtype=rd)
        elif scaleType=='free':
            params['log_kPeak']=jnp.asarray(np.log(kPeak0),dtype=rd)
        if bPhase:
            params['phase']=jnp.zeros(nTot,dtype=rd)
        if self.nrn.bParams:
            params['p']=self._p0()

        params=self._train_generated(params,'multiscale',cfg,stimVal=stimVal)
        self._set_generated(self._generated_filters('multiscale',params,cfg),params)

        mother=np.asarray(self._tapered_mothers(params,cfg))
        if nMothers==1:
            mother=mother[0]                                                      # single mother: [ nKnot (x nKnotTheta) ]
        if scaleType=='tied':
            r=float(1+np.exp(np.asarray(params['log_ratio_m1'])))
            kp=float(np.exp(np.asarray(params['log_kTop'])))/r**scaleExp
        elif scaleType=='fixed':
            r,kp=None,kPeak0
        else:
            r,kp=None,np.exp(np.asarray(params['log_kPeak']))
        tile=lambda v: np.tile(np.asarray(v),nMothers)                           # per mother -> per filter (mother first)
        out={'mother':mother,'log_freq_knots':ug,'k_peak':tile(kp),'ratio':r,'scaleType':scaleType,'fourierType':fourierType}
        out['scale_step']=tile(scaleExp)
        out['nMothers']=nMothers
        out['edgeTaper']=float(edgeTaper)
        out['mother_index']=np.repeat(np.arange(nMothers),n)
        if bPhase:
            out['phase']=np.asarray(params['phase'])
        if b2D:
            out['angle_knots']=np.linspace(-np.pi/2,np.pi/2,nKnotTheta)
            out['orientations']=tile(orientations)
        if bGrid:
            out['nScales'],out['nOrientations'],out['bInterleave']=nScales,nOrientations,bool(bInterleave)
            out['interleaved']=tile(scaleExp%1!=0)
        self.multiscale_out=out

    def multiscale_values(self):
        """the learned mother filter (complex knot values and their log-frequency, and angle, positions) and the peak
        frequencies (cycles/sample) and ratio of the last train_multiscale"""
        if getattr(self,'multiscale_out',None) is None:
            raise Exception('train_multiscale has not been run')
        return self.multiscale_out

    def parametric_values(self):
        """interpretable parameters of the last train_parametric: peak frequencies (cycles/sample), shapes, orientations"""
        if getattr(self,'param_out',None) is None:
            raise Exception('train_parametric has not been run')
        return self.param_out

    @_logged_training
    def train_parametric(self,n,family='morse',fourierType=2,bTied=True,orientations=None,init=None,dtype=None,stimVal=None,
                         bPhase=False):
        """
        learn a parametric filter bank instead of free filters: generalized Morse, |H(k)| = (k/kp)^b exp((b/gamma)(1-(k/kp)^gamma)),
        or log-Gabor, exp(-log(k/kp)^2/(2 sigma_u^2)), with a gaussian angular profile (width sigma_theta, one-sided) around
        each filter's orientation for 2D stimuli. With bTied, the filters are dilations of one mother filter with peak
        frequencies kTop/ratio^j (parameters kTop, ratio, and one shape); otherwise every filter has its own peak and shape.
        orientations [ nF ] radians from the first stimulus axis (2D; default 0). init overrides starting values (kTop, ratio,
        gamma, b, sigma_u, sigma_theta). Uses this unit's Optimizer (optimizerType, lRate0, nIterMax, nStepsPerChunk,
        patience with stimVal). The learned filters become ordinary filters (unit.out), so evaluation, saving, and
        train_recurse (free refinement from the parametric solution) work as usual; parametric_values() returns the
        parameters. Not implemented for split stimuli.
        bPhase - also learn a phase per filter, which multiplies its spectrum by exp(i phase): the profiles are otherwise
                 zero-phase (even filters with fourierType=1; cosine/sine pairs with fourierType=2), and a learned phase
                 gives odd or intermediate filters, or rotates each quadrature pair (which matters with 'phase'
                 normalization and pooled readouts, and through the response-dependent noise)
        """
        if fourierType not in (1,2):
            raise Exception('train_parametric learns in the fourier domain: fourierType must be 1 or 2')
        self.pool_p=self.nrn_p=None
        self._finalize(n,np.arange(n),fourierType=fourierType,dtype=dtype,bSplit=False)
        if len(self.filter.pix_dims) not in (1,2):
            raise Exception('train_parametric supports 1D and 2D stimuli')
        b2D=len(self.filter.pix_dims)==2
        orientations=np.zeros(n) if orientations is None else np.asarray(orientations,dtype=float)
        if b2D and orientations.shape!=(n,):
            raise Exception('orientations must have one value per filter')
        params=self._parametric_init(family,n,bTied,init,b2D)
        if bPhase:
            params['phase']=jnp.zeros(n,dtype=jnp.finfo(self.nrn.dtype).dtype)
        if self.nrn.bParams:
            params['p']=self._p0()
        cfg=dict(family=family,n=n,bTied=bTied,orientations=orientations)
        params=self._train_generated(params,'parametric',cfg,stimVal=stimVal)
        self._set_generated(self._generated_filters('parametric',params,cfg),params)
        e=lambda k: np.exp(np.asarray(params[k]))
        out={'family':family,'bTied':bTied,'fourierType':fourierType}
        if bTied:
            out['ratio']=float(1+e('log_ratio_m1'))
            out['k_peak']=float(e('log_kTop'))/out['ratio']**np.arange(n)
        else:
            out['k_peak']=e('log_kPeak')
        if family=='morse':
            out['gamma'],out['b']=e('log_gamma'),e('log_b')
        else:
            out['sigma_u']=e('log_sigma_u')
        if b2D:
            out['sigma_theta']=e('log_sigma_theta')
            out['orientations']=orientations
        if bPhase:
            out['phase']=np.asarray(params['phase'])
        self.param_out=out


__all__=['_Banks']
